
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { ExtendedDatabase } from './types-extension';

const SUPABASE_URL = "https://dqyqqvewherwzfeynaab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxeXFxdmV3aGVyd3pmZXluYWFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MTE5ODQsImV4cCI6MjA1MjE4Nzk4NH0.1zBDn-7Lmwf4h47cNqJYPK45IZctFkW4sPqIILpIGHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);
